# Navigation
curriculum_title:
  default: Visit the Curriculum
  description: "This text will be displayed in the curriculum navigation item"
curriculum_title_short:
  default: Curriculum
  description: "This is the short version of curriculum title used for mobile devices"
curriculum_src:
  default: https://www.freecodecamp.org/learn
  description: "This the link to related language curriculum"

# Analytics
Google_Tag_Manager:
  default: ""
  description: "Google Tag Manager ID"

# Footer description section
footer_paragraph_1:
  default: "freeCodeCamp is a donor-supported tax-exempt 501(c)(3) nonprofit
    organization (United States Federal Tax Identification Number:
    82-0779546)"
  description: "First footer paragraph"
footer_paragraph_2:
  default:
    "Our mission: to help people learn to code for free. We accomplish this
    by creating thousands of videos, articles, and interactive coding
    lessons - all freely available to the public. We also have thousands
    of freeCodeCamp study groups around the world."
  description: "Second footer paragraph"
footer_paragraph_3:
  default: "Donations to freeCodeCamp go toward our education initiatives, and
    help pay for servers, services, and staff."
  description: "Second footer paragraph"
footer_donation_cta:
  default: "You can make a tax-deductible donation here."
  description: "Footer donation paragraph"

# Footer columns section
footer_columns_header:
  default: "Trending Guides"
  description: "Header for footer link columns"
article0title: "Best Python IDEs"
article0link: "https://www.freecodecamp.org/news/python-ide-best-ides-and-editors-for-python/"
article1title: "Git List Branches"
article1link: "https://www.freecodecamp.org/news/git-list-branches-how-to-show-all-remote-and-local-branch-names/"
article2title: "Java Enum Example"
article2link: "https://www.freecodecamp.org/news/java-enum-enumeration-in-java-example/"
article3title: "Checkmark in HTML"
article3link: "https://www.freecodecamp.org/news/checkmark-symbol-html-for-checkmark-unicode/"
article4title: "What is an iframe?"
article4link: "https://www.freecodecamp.org/news/what-is-an-iframe-html-example/"
article5title: "Python List Length"
article5link: "https://www.freecodecamp.org/news/python-list-length-how-to-get-the-size-of-a-list-in-python/"
article6title: "Python String to Int"
article6link: "https://www.freecodecamp.org/news/python-string-to-int-convert-a-string-example/"
article7title: "Int to String in C++"
article7link: "https://www.freecodecamp.org/news/int-to-string-in-cpp-how-to-convert-an-integer-with-tostring/"
article8title: "CSS Margin vs Padding"
article8link: "https://www.freecodecamp.org/news/css-margin-vs-padding-what-is-the-difference/"
article9title: "HTML Starter Template"
article9link: "https://www.freecodecamp.org/news/html-starter-template-a-basic-html5-boilerplate-for-index-html/"
article10title: "Python Index"
article10link: "https://www.freecodecamp.org/news/python-index-find-index-of-element-in-list/"
article11title: "What is HTML?"
article11link: "https://www.freecodecamp.org/news/what-is-html-what-does-html-stand-for-solved/"
article12title: "What is UTF-8?"
article12link: "https://www.freecodecamp.org/news/what-is-utf-8-character-encoding/"
article13title: "SQL Inner Join"
article13link: "https://www.freecodecamp.org/news/sql-inner-join-how-to-join-3-tables-in-sql-and-mysql/"
article14title: "What is ANAME?"
article14link: "https://www.freecodecamp.org/news/what-is-aname-aname-record-dns-tutorial/"
article15title: "HTML Dot Symbol"
article15link: "https://www.freecodecamp.org/news/dot-symbol-bullet-point-in-html-unicode/"
article16title: "indexOf in Java"
article16link: "https://www.freecodecamp.org/news/indexof-in-java-how-to-find-the-index-of-a-string-in-java/"
article17title: "Image File Types"
article17link: "https://www.freecodecamp.org/news/image-file-types-picture-format-extensions-jpeg-gif-png-svg-tiff/"
article18title: "SOLID Principles"
article18link: "https://www.freecodecamp.org/news/solid-principles-single-responsibility-principle-explained/"
article19title: "How to Flush DNS"
article19link: "https://www.freecodecamp.org/news/flushdns-how-to-flush-dns-with-the-windows-ipconfig-flushdns-command/"
article20title: "Rubber Duck Debugging"
article20link: "https://www.freecodecamp.org/news/rubber-duck-debugging/"
article21title: "SQL vs NoSQL Databases"
article21link: "https://www.freecodecamp.org/news/relational-vs-nonrelational-databases-difference-between-sql-db-and-nosql-db/"
article22title: "Python For Loop Example"
article22link: "https://www.freecodecamp.org/news/python-for-loop-example-how-to-write-loops-in-python/"
article23title: "Int Object Not Iterable"
article23link: "https://www.freecodecamp.org/news/int-object-is-not-iterable-python-error-solved/"
article24title: "How to Type Vertical Bar"
article24link: "https://www.freecodecamp.org/news/how-to-type-the-vertical-line-bar-character-on-a-keyboard/"
article25title: "DNS Server Not Responding"
article25link: "https://www.freecodecamp.org/news/dns-server-not-responding-service-unavailable-dns-failure-solved/"
article26title: "Module Exports in Node.js"
article26link: "https://www.freecodecamp.org/news/module-exports-how-to-export-in-node-js-and-javascript/"
article27title: "Computer Skills for Résumé"
article27link: "https://www.freecodecamp.org/news/computer-skills-for-resume-software-skill-proficiency-guide/"
article28title: "Force Delete a Windows File"
article28link: "https://www.freecodecamp.org/news/how-to-force-delete-a-file-windows-command-prompt-cmd-delete/"
article29title: "Inspect an Element in Chrome"
article29link: "https://www.freecodecamp.org/news/how-to-inspect-an-element-chrome-shortcut/"

footer_our_org_header:
  default: "Our Nonprofit"
  description: "Title for organizational links"
footer_about_link: "https://www.freecodecamp.org/news/about/"
footer_about_text: "About"
footer_Alumni_Network_link: "https://www.linkedin.com/school/free-code-camp/people/"
footer_Alumni_Network_text: "Alumni Network"
footer_Open_Source_link: "https://github.com/freeCodeCamp/"
footer_Open_Source_text: "Open Source"
footer_Shop_link: "https://www.freecodecamp.org/shop/"
footer_Shop_text: "Shop"
footer_Support_link: "https://www.freecodecamp.org/news/support/"
footer_Support_text: "Support"
footer_Sponsors_link: "https://www.freecodecamp.org/news/sponsors/"
footer_Sponsors_text: "Sponsors"
footer_Academic_Honesty_link: "https://www.freecodecamp.org/news/academic-honesty-policy/"
footer_Academic_Honesty_text: "Academic Honesty"
footer_Code_of_Conduct_link: "https://www.freecodecamp.org/news/code-of-conduct/"
footer_Code_of_Conduct_text: "Code of Conduct"
footer_Privacy_Policy_link: "https://www.freecodecamp.org/news/privacy-policy/"
footer_Privacy_Policy_text: "Privacy Policy"
footer_Terms_of_Service_link: "https://www.freecodecamp.org/news/terms-of-service/"
footer_Terms_of_Service_text: "Terms of Service"
footer_Copyright_Policy_link: "https://www.freecodecamp.org/news/copyright-policy/"
footer_Copyright_Policy_text: "Copyright Policy"
