# Navigation
curriculum_title:
  default: Visit the Curriculum
  description: "This text will be displayed in the curriculum navigation item"
curriculum_title_short:
  default: Curriculum
  description: "This is the short version of curriculum title used for mobile devices"
curriculum_src:
  default: https://www.freecodecamp.org/learn
  description: "This the link to related language curriculum"

# Analytics
Google_Tag_Manager:
  default: ""
  description: "Google Tag Manager ID"

# Footer description section
footer_paragraph_1:
  default: "freeCodeCamp is a donor-supported tax-exempt 501(c)(3) nonprofit
    organization (United States Federal Tax Identification Number:
    82-0779546)"
  description: "First footer paragraph"
footer_paragraph_2:
  default:
    "Our mission: to help people learn to code for free. We accomplish this
    by creating thousands of videos, articles, and interactive coding
    lessons - all freely available to the public. We also have thousands
    of freeCodeCamp study groups around the world."
  description: "Second footer paragraph"
footer_paragraph_3:
  default: "Donations to freeCodeCamp go toward our education initiatives, and
    help pay for servers, services, and staff."
  description: "Second footer paragraph"
footer_donation_cta:
  default: "You can make a tax-deductible donation here."
  description: "Footer donation paragraph"

# Footer columns section
footer_columns_header:
  default: "Trending Guides"
  description: "Header for footer link columns"
article0title: "JavaScript split()"
article0link: "https://www.freecodecamp.org/news/javascript-split-a-string-string-to-array-js-method/"
article1title: "HTML Bullet Points"
article1link: "https://www.freecodecamp.org/news/html-bullet-points-how-to-create-an-unordered-list-with-the-ul-tag-example/"
article2title: "What is UX Design?"
article2link: "https://www.freecodecamp.org/news/user-experience-design-what-does-a-ux-designer-do/"
article3title: "Dark Mode on Google"
article3link: "https://www.freecodecamp.org/news/how-to-turn-on-dark-mode-on-google-chrome-black-theme-tutorial/"
article4title: "Contraction Grammar "
article4link: "https://www.freecodecamp.org/news/what-is-a-contraction-grammar-and-definition/"
article5title: "What is a JSON file?"
article5link: "https://www.freecodecamp.org/news/what-is-a-json-file-example-javascript-code/"
article6title: "Python String Format"
article6link: "https://www.freecodecamp.org/news/python-string-format-python-s-print-format-example/"
article7title: "Python Tuple vs List"
article7link: "https://www.freecodecamp.org/news/python-tuple-vs-list-what-is-the-difference/"
article8title: "What is Programming?"
article8link: "https://www.freecodecamp.org/news/what-is-programming/"
article9title: "Check GPU in Windows"
article9link: "https://www.freecodecamp.org/news/what-graphics-card-do-i-have-how-to-check-your-gpu-in-windows-10-pc-guide/"
article10title: "Span HTML"
article10link: "https://www.freecodecamp.org/news/span-html-how-to-use-the-span-tag-with-css/"
article11title: "SQL Count"
article11link: "https://www.freecodecamp.org/news/sql-count-how-to-select-sum-and-average-rows-in-sql/"
article12title: "HTML Comment"
article12link: "https://www.freecodecamp.org/news/html-comment-how-to-comment-out-a-line-or-tag-in-html/"
article13title: "Python strip()"
article13link: "https://www.freecodecamp.org/news/python-strip-how-to-trim-a-string-or-line/"
article14title: "HTML Select Tag"
article14link: "https://www.freecodecamp.org/news/html-select-tag-how-to-make-a-dropdown-menu-or-combo-list/"
article15title: "Insert into SQL"
article15link: "https://www.freecodecamp.org/news/insert-into-sql-how-to-insert-into-a-table-query-example-statement/"
article16title: "MVC Architecture"
article16link: "https://www.freecodecamp.org/news/mvc-architecture-what-is-a-model-view-controller-framework/"
article17title: "What is the DOM?"
article17link: "https://www.freecodecamp.org/news/what-is-the-dom-document-object-model-meaning-in-javascript/"
article18title: "HTML Button Type"
article18link: "https://www.freecodecamp.org/news/html-button-type-how-to-add-buttons-to-your-website/"
article19title: "SCP Linux Command"
article19link: "https://www.freecodecamp.org/news/scp-linux-command-example-how-to-ssh-file-transfer-from-remote-to-local/"
article20title: "HTML File Text Editor"
article20link: "https://www.freecodecamp.org/news/html-file-text-editor-how-to-open-web-page-code-in-windows-notepad/"
article21title: "Responsive Web Design"
article21link: "https://www.freecodecamp.org/news/responsive-web-design-modern-website-code-for-beginners/"
article22title: "Online Coding Classes"
article22link: "https://www.freecodecamp.org/news/online-coding-classes-for-beginners-2022-guide/"
article23title: "Python String to Array"
article23link: "https://www.freecodecamp.org/news/python-string-to-array-how-to-convert-text-to-a-list/"
article24title: "Lambda Function Python"
article24link: "https://www.freecodecamp.org/news/lambda-function-in-python-example-syntax/"
article25title: "SQL Distinct Statement"
article25link: "https://www.freecodecamp.org/news/sql-distinct-statement-how-to-query-select-and-count/"
article26title: "HEIC to JPG on Windows"
article26link: "https://www.freecodecamp.org/news/convert-heic-to-jpg-on-windows-heic-file-format-on-pc/"
article27title: "Insert Checkbox in Word"
article27link: "https://www.freecodecamp.org/news/insert-a-checkbox-in-word-how-to-add-a-checkmark-in-microsoft-word/"
article28title: "Drop Pin on Google Maps"
article28link: "https://www.freecodecamp.org/news/how-to-drop-a-pin-on-google-maps/"
article29title: "Rotate Screen Windows 10"
article29link: "https://www.freecodecamp.org/news/rotate-screen-in-windows-10-how-to-flip-your-monitor-orientation-90-degrees/"

footer_our_org_header:
  default: "Our Nonprofit"
  description: "Title for organizational links"
footer_about_link: "https://www.freecodecamp.org/news/about/"
footer_about_text: "About"
footer_Alumni_Network_link: "https://www.linkedin.com/school/free-code-camp/people/"
footer_Alumni_Network_text: "Alumni Network"
footer_Open_Source_link: "https://github.com/freeCodeCamp/"
footer_Open_Source_text: "Open Source"
footer_Shop_link: "https://www.freecodecamp.org/shop/"
footer_Shop_text: "Shop"
footer_Support_link: "https://www.freecodecamp.org/news/support/"
footer_Support_text: "Support"
footer_Sponsors_link: "https://www.freecodecamp.org/news/sponsors/"
footer_Sponsors_text: "Sponsors"
footer_Academic_Honesty_link: "https://www.freecodecamp.org/news/academic-honesty-policy/"
footer_Academic_Honesty_text: "Academic Honesty"
footer_Code_of_Conduct_link: "https://www.freecodecamp.org/news/code-of-conduct/"
footer_Code_of_Conduct_text: "Code of Conduct"
footer_Privacy_Policy_link: "https://www.freecodecamp.org/news/privacy-policy/"
footer_Privacy_Policy_text: "Privacy Policy"
footer_Terms_of_Service_link: "https://www.freecodecamp.org/news/terms-of-service/"
footer_Terms_of_Service_text: "Terms of Service"
footer_Copyright_Policy_link: "https://www.freecodecamp.org/news/copyright-policy/"
footer_Copyright_Policy_text: "Copyright Policy"
