# Navigation
curriculum_title:
  default: Visit the Curriculum
  description: "This text will be displayed in the curriculum navigation item"
curriculum_title_short:
  default: Curriculum
  description: "This is the short version of curriculum title used for mobile devices"
curriculum_src:
  default: https://www.freecodecamp.org/learn
  description: "This the link to related language curriculum"

# Analytics
Google_Tag_Manager:
  default: ""
  description: "Google Tag Manager ID"

# Footer description section
footer_paragraph_1:
  default: "freeCodeCamp is a donor-supported tax-exempt 501(c)(3) nonprofit
    organization (United States Federal Tax Identification Number:
    82-0779546)"
  description: "First footer paragraph"
footer_paragraph_2:
  default:
    "Our mission: to help people learn to code for free. We accomplish this
    by creating thousands of videos, articles, and interactive coding
    lessons - all freely available to the public. We also have thousands
    of freeCodeCamp study groups around the world."
  description: "Second footer paragraph"
footer_paragraph_3:
  default: "Donations to freeCodeCamp go toward our education initiatives, and
    help pay for servers, services, and staff."
  description: "Second footer paragraph"
footer_donation_cta:
  default: "You can make a tax-deductible donation here."
  description: "Footer donation paragraph"

# Footer columns section
footer_columns_header:
  default: "Trending Guides"
  description: "Header for footer link columns"
article0title: "Python Comment Block"
article0link: "https://www.freecodecamp.org/news/python-comment-block-how-to-comment-out-code-in-python/"
article1title: "Python Code Examples"
article1link: "https://www.freecodecamp.org/news/python-code-examples-simple-python-program-example/"
article2title: "Types of Hard Drives"
article2link: "https://www.freecodecamp.org/news/types-of-hard-drives-sata-pata-scsi-and-more-2/"
article3title: "Python List .remove()"
article3link: "https://www.freecodecamp.org/news/python-list-remove-how-to-remove-an-item-from-a-list-in-python/"
article4title: "Python Concat Strings"
article4link: "https://www.freecodecamp.org/news/python-concatenate-strings-how-to-combine-and-append-strings-in-python/"
article5title: "pip Command Not Found"
article5link: "https://www.freecodecamp.org/news/pip-command-not-found-mac-and-linux-error-solved/"
article6title: "Sort a List in Python"
article6link: "https://www.freecodecamp.org/news/python-sort-how-to-sort-a-list-in-python/"
article7title: "502 Bad Gateway Error"
article7link: "https://www.freecodecamp.org/news/502-bad-gateway-error-solved/"
article8title: "Resize Image Tutorial"
article8link: "https://www.freecodecamp.org/news/how-to-resize-an-image-without-losing-quality/"
article9title: "Python Compare Strings"
article9link: "https://www.freecodecamp.org/news/python-compare-strings-how-to-check-for-string-equality/"
article10title: "Python Sleep"
article10link: "https://www.freecodecamp.org/news/python-sleep-time-sleep-in-python/"
article11title: "HTTP Error 504"
article11link: "https://www.freecodecamp.org/news/http-error-504-gateway-timeout-status-code-explained/"
article12title: "Git Undo Merge"
article12link: "https://www.freecodecamp.org/news/git-undo-merge-how-to-revert-the-last-merge-commit-in-git/"
article13title: "Python Datetime"
article13link: "https://www.freecodecamp.org/news/how-to-get-the-current-time-in-python-with-datetime/"
article14title: "Comment Out HTML"
article14link: "https://www.freecodecamp.org/news/comment-out-html-code-example/"
article15title: "Else-If in Python"
article15link: "https://www.freecodecamp.org/news/else-if-in-python-python-if-statement-example-syntax/"
article16title: "Design Principles"
article16link: "https://www.freecodecamp.org/news/design-principles-a-list-of-the-principles-of-design/"
article17title: "SQL Contains String"
article17link: "https://www.freecodecamp.org/news/sql-contains-string-sql-regex-example-query/"
article18title: "Extern in C and C++"
article18link: "https://www.freecodecamp.org/news/extern-keyword-function-tutorial/"
article19title: "Frontend vs Backend"
article19link: "https://www.freecodecamp.org/news/frontend-vs-backend-whats-the-difference/"
article20title: "Send Large Video Files"
article20link: "https://www.freecodecamp.org/news/how-to-send-large-video-files-share-a-big-file-with-email/"
article21title: "Create a Dict in Python"
article21link: "https://www.freecodecamp.org/news/create-a-dictionary-in-python-python-dict-methods/"
article22title: "Create a List in Python"
article22link: "https://www.freecodecamp.org/news/create-a-list-in-python-lists-in-python-syntax/"
article23title: "Python Break & Continue"
article23link: "https://www.freecodecamp.org/news/python-break-and-python-continue-how-to-skip-to-the-next-function/"
article24title: "Python Multiline Comment"
article24link: "https://www.freecodecamp.org/news/python-multiline-comment-how-to-comment-out-multiple-lines-in-python/"
article25title: "What’s a Full Stack Dev?"
article25link: "https://www.freecodecamp.org/news/what-is-a-full-stack-developer-full-stack-engineer-guide/"
article26title: "How to Flush DNS on a Mac"
article26link: "https://www.freecodecamp.org/news/how-to-flush-dns-on-mac-macos-clear-dns-cache/"
article27title: "Remove Duplicates in Excel"
article27link: "https://www.freecodecamp.org/news/how-to-remove-duplicates-in-excel-delete-duplicate-rows-tutorial/"
article28title: "Hanging Indent Google Docs"
article28link: "https://www.freecodecamp.org/news/how-to-do-a-hanging-indent-in-google-docs/"
article29title: "How to Find Remote Jobs"
article29link: "https://www.freecodecamp.org/news/remote-work-how-to-find-remote-working-jobs-from-home/"

footer_our_org_header:
  default: "Our Nonprofit"
  description: "Title for organizational links"
footer_about_link: "https://www.freecodecamp.org/news/about/"
footer_about_text: "About"
footer_Alumni_Network_link: "https://www.linkedin.com/school/free-code-camp/people/"
footer_Alumni_Network_text: "Alumni Network"
footer_Open_Source_link: "https://github.com/freeCodeCamp/"
footer_Open_Source_text: "Open Source"
footer_Shop_link: "https://www.freecodecamp.org/shop/"
footer_Shop_text: "Shop"
footer_Support_link: "https://www.freecodecamp.org/news/support/"
footer_Support_text: "Support"
footer_Sponsors_link: "https://www.freecodecamp.org/news/sponsors/"
footer_Sponsors_text: "Sponsors"
footer_Academic_Honesty_link: "https://www.freecodecamp.org/news/academic-honesty-policy/"
footer_Academic_Honesty_text: "Academic Honesty"
footer_Code_of_Conduct_link: "https://www.freecodecamp.org/news/code-of-conduct/"
footer_Code_of_Conduct_text: "Code of Conduct"
footer_Privacy_Policy_link: "https://www.freecodecamp.org/news/privacy-policy/"
footer_Privacy_Policy_text: "Privacy Policy"
footer_Terms_of_Service_link: "https://www.freecodecamp.org/news/terms-of-service/"
footer_Terms_of_Service_text: "Terms of Service"
footer_Copyright_Policy_link: "https://www.freecodecamp.org/news/copyright-policy/"
footer_Copyright_Policy_text: "Copyright Policy"
